### ISSUE TITLE
use roter without binding to app instance

### ISSUE THREAD

**Issue by platinumindustries** [hanrea/koa2-routing#3]
is it possible to use this router without binding to app instance?
I have an app that matches the middleware to be called and calls that middleware then leaves the rest of the logic to the middleware. Supposing I was to use the router in said middleware without the need to hook it to app instance, how do i do that?

**Comment by hanrea** [comment]
like this 

```javascript
var Koa = require('koa'),
	routing = require('koa2-routing');
var app = new Koa();
app.use(routing(app));
```

**Comment by hanrea** [comment]
app.use(    routing(     app  )  );     // Pay attention to this line

**Comment by platinumindustries** [comment]
Like bind it to a different object instance that doesnt have a **ctx object**
`routing = require('koa2-routing');
var app_instance = {}
routing(app_instance)
app_instance.route('random/:path').get( async ctx -> {} )
`

**Comment by hanrea** [comment]
In this version, need bind 2 time. like this`app.use(routing(app));  1: `routing(app)  2:`app.use(routing(app));`  . This is in Koa-routing V1 solution,if you want change ,you can modify 

https://github.com/hanrea/koa2-routing/blob/8d7f8cf4ae7d380f0d8d697ea71c432f62cdda26/lib/router.js#L35   


In this function `app`has defined.
